### ISSUE TITLE
Please document

### ISSUE THREAD

**Issue by JJ** [eyeos/spice-web-client#4]
At leas a line describing each and every function and what they do. It's missing in the files I've checked.

**Comment by anortef** [comment]
I think that is one of the purposes of having unit tests. I mean, if I want to know how a class operates I will look at the test. That's how I see it.

**Comment by JJ** [comment]
Sure it is, if there's some documentation indicating that fact. However, the best way of documenting a function is, well, describing it next to where the function is actually implemented.

**Comment by anortef** [comment]
But a test is a live thing that evolves with the code it tests and the other thing is easily ignored and can become outdated pretty quickly.

**Comment by anortef** [comment]
http://elegantcode.com/2010/04/25/if-self-documenting-code-is-the-what-unit-tests-are-the-why/

This article explains what I'm trying to say.

**Comment by JJ** [comment]
It's pretty clear what you're trying to say; you don't want to write
documentation.
Tests are OK if their coverage is high (which we don't know, because we
have no idea of the coverage of those tests) and if you document it
somewhere saying: "Want to know how to do x or y with this? Check out the
tests here and here".
Besides, it depends on the tests. BDD tests are pretty clear. These are not
so much.
At the end of the day it boils down to: how hard do you want people to try
to do stuff with this? Documentation lowers the threshold, it shows point
of entry, it highlights the path... reading documentation trumps reading
code any time.
But your code, your issue. If you don't agree, just close this.

**Comment by anortef** [comment]
"It's pretty clear what you're trying to say; you don't want to write
documentation." 
That's not what I'm trying to say, I though we were discussing if writing documentation is pointless or not or in how much degree documentation should be written.

And I don't want to continue arguing with you and your bad manners I believe I haven been always polite in my answers taking into account your point of view before submitting an answer but you clearly doesn't intend into discuss anything, you just want to make your point that you believe is the universal truth so I will close this issue and move along.
